version: '3'

services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - web

  web:
    container_name: "fast_api_proxy"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./src:/opt/app"
    ports:
      - 8000:8000
    command: "sh -c 'uvicorn main:app --reload --workers 3 --host 0.0.0.0 --port 8000'"
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:latest
    restart: always
    hostname: redis
    ports:
      - 6379:6379
